### ISSUE TITLE
showMenu所顯示的隊伍跟分數與實際畫面呈現時分數顛倒了

### ISSUE THREAD

**Issue by uiloon** [yungshenglu/NBA-Boxscore#2]
清單畫面
![image](https://user-images.githubusercontent.com/536676/111281521-fbe12a80-8677-11eb-884a-663440bee8d6.png)

實際畫面
![image](https://user-images.githubusercontent.com/536676/111281549-056a9280-8678-11eb-8b97-8fab83ffb4da.png)

**Comment by davidyslu** [comment]
@uiloon 
已經於 `v0.0.2`中修復完畢，可以安裝最新版喔 🎉

**Comment by uiloon** [comment]
OK
